apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-project
spec:
  selector:
    matchLabels: 
      app: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-cd
        image: localregistry:5000/nodejs
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 7

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
  - port: 3000
    nodePort: 30099
    targetPort: 3000
  type:  NodePort

