apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-project
spec:
  selector:
    matchLabels: 
      app: nodejs
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-cd
        image: nodejs_project
